elevation-plot/map.js
route/map.js

feat: rainbow road

---

elevation-plot/elevationGraph.js
elevation-plot/queries.js

The property name avSpeed has been changed to average speed

fix: average speed

---

public/stations-along-route/index.html
public/stations-along-route/style.css
stations-along-route/index.js
stations-along-route/map.js

The switch was active before the map was loaded.

fix: switch to show alternatives

---

public/state-of-charge/index.html
public/state-of-charge/style.css
state-of-charge/client.js
state-of-charge/index.js
state-of-charge/slider.js

Increased soc at the start as it can not be 0. Route can't be calculated then. 
Also restructured a bit code to keep it consistent.

fix: increased soc at start as it can not be 0

---

stations-along-route/map.js
stations-along-route/queries.js

I changed the SOC to a lower number, this way you can also see a required charging station and not just alternatives.

fix: soc to show charging station

---

alternative-routes/map.js
car/cars.js
car/index.js
car/queries.js
elevation-plot/map.js
public/car/images/info.svg
public/car/index.html
public/car/style.css
route/map.js
state-of-charge/map.js
station-info/map.js
stations-along-route/map.js
stations/map.js
tile-server/map.js

The car example needs to updated after the next release. This will affect the carList query that is used in this example. The data that we are removing now is still available in the car query.

fix: car example updated

---

public/route/index.html
public/route/style.css
route/index.js

Added "Drive with Google" button that exports route to Google Maps.

feat: added 'Drive with Google' button to route example

---

route/index.js

I have added www to the google maps URL, to make sure the link also works for Android

fix: route url

---

package.json
yarn.lock

Upgrade to the new version of Mapbox

build: updated to mapbox gl v2

---

alternative-routes/README.md
alternative-routes/queries.js
public/alternative-routes/index.html

fix: change route to Berlin

---

car/cars.js
car/index.js
car/queries.js
public/car/index.html
public/car/style.css

I have implemented the new car query. I have also added more fields that are available in de carList query. In the future I would like to add all connectors, for now just the first one is added (This is the same as before). Please test the changes on the staging environment.

fix: update to new car query

---

car-list/index.js
car-list/queries.js

This PR makes sure we only show no longer for sale / currently on sale vehicles.

Included car filters on the car example 

---

car/README.md
car/cars.js
car/client.js
car/index.js
car/queries.js
public/car-list/style.css
public/car/index.html
public/car/style.css

New way of fetching car details data

---

elevation-plot/elevationGraph.js
route/index.js
route/queries.js
state-of-charge/client.js
state-of-charge/queries.js

It is no longer necessary to do an extra query. Even if the route is already calculated before you subscribe to it you will receive the route.

fix: remove extra query

---

station-info/map.js
stations/map.js
tile-server/map.js

fix: increase offset

---

public/car-list/index.html
public/car/index.html

Car-list link was not working. and car pointed to the wrong github repo

fix: link was not working

---

battery-capacity/queries.js

The SOC needs to be equal to the capacity.

fix: make sure SOC is equal to capacity

---

preferred-operator/README.md
preferred-operator/client.js
preferred-operator/index.js
preferred-operator/interface.js
preferred-operator/map.js
preferred-operator/queries.js
public/preferred-operator/index.html
public/preferred-operator/style.css

Preparation for next release which includes an improved operator search and the ability to filter on countries.

New operator update is included in the example

---

examples/5.isolines/1.isoline/map.js
examples/5.isolines/1.isoline/queries.js

Updated the example based on the API updates.

fix: update example

---

.github/workflows/deploy.yml
.idea/.gitignore
.idea/inspectionProfiles/Project_Default.xml
examples/4.tile-service/1.tile-server/index.js
examples/4.tile-service/3.tile-coordinates/index.js

Related to https://github.com/chargetrip/developers-v2/pull/140

feat(tile): add tile coordinates example
